# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'pidebugger' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pidebugger
  pod 'Socket.IO-Client-Swift', '~> 8.1.2' # Or latest version
  pod 'NMSSH', '~> 2.2.5'

  target 'pidebuggerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pidebuggerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
